[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "smalldi"
version = "0.3.0"
description = "Annotation-driven dependency injection for Python with Provide[T] type hints and decorators."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [{ name = "Anna-Sofia Kasierocka", email = "f104a@f104a.io" }]
keywords = [
  "dependency injection", "di", "typing", "annotations",
  "dependency-injection", "inversion-of-control", "ioc", "singleton", "minimal", "lightweight",
  "decorators", "type-hints", "zero-dependency",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Typing :: Typed",
  "Topic :: Software Development :: Libraries",
  "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/0xf104a/smalldi"
Documentation = "https://github.com/0xf104a/smalldi#readme"
Source = "https://github.com/0xf104a/smalldi"
Issues = "https://github.com/0xf104a/smalldi/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/smalldi"]
include = [
  "src/smalldi/py.typed",
]

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/README.md",
  "/LICENSE",
  "/pyproject.toml",
  "/CHANGELOG.md",
]